//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.06 at 07:19:09 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = LINK.ORDER, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ua.lb4.restserver.model.order;

import ua.lb4.restserver.LINK;